config/routes.rb
Rails.application.routes.draw do

  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
    # SELECT * FROM todo WHERE id='params_id'
  end

  def new
    @todos = Todo.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to posts_path
    else
      render  :new
    end
  end

  private

    def item_params
      params.require(:item).permit(:item, :notes)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>Todos</h1>
<p><%= link_to 'New Todo', new_todo_path %></p>
<% @todos.each do |todo|%>
<h2><%= todo.item %></h2>
<h3><%= todo.notes %></h2>
  <%= link_to 'Show Todo', todo_path(todo)%>
  <%end%>

app/views/todos/new.html.erb
<h1>New Item</h1>
<%= form_for @todo do |f| %>
<%= f.label :item %>:
<%= f.text_field :item %>

<%= f.label :notes %>
<%= f.text_field :notes%>

<%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1>Item</h1>
<h2><%= @todo.item %></h2>
<h3><%= @todo.notes %></h2>
  <%= link_to 'Back', todos_path %>